{% set name = "vegafusion-jupyter" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 66de1a99b54bcbc6dd7e8d9511e57e5a1ed2052b69e7a0fc906f26558810905f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - jupyterlab ==3
    - jupyter-packaging ==0.7.9
  run:
    - altair >=4.2.0
    - ipywidgets >=7.0.0
    - python >=3.7
    - vegafusion >=1.0

test:
  imports:
    - vegafusion_jupyter
    - vegafusion.jupyter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://vegafusion.io
  summary: Altair Jupyter Widget library that relies on VegaFusion for server-side calculations
  license: BSD-3-Clause
  license_file: LICENSE.txt
  doc_url: https://vegafusion.io
  dev_url: https://github.com/hex-inc/vegafusion

extra:
  recipe-maintainers:
    - jonmmease
