{% set name = "vegafusion-jupyter" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 033696bb28ad34c722e46a2be33e57987cdb5aa10d2520f71e0fde7642153e56

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - jupyter-packaging
    - pip
    - python >=3.7
  run:
    - altair >=4.2.0
    - ipywidgets >=7.0.0
    - python >=3.7
    - vegafusion

test:
  imports:
    - vegafusion_jupyter
    - vegafusion.jupyter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://vegafusion.io
  summary: Altair Jupyter Widget library that relies on VegaFusion for server-side calculations
  license: AGPL-3.0-or-later
  license_file: LICENSE.txt
  doc_url: https://vegafusion.io
  dev_url: https://github.com/vegafusion/vegafusion

extra:
  recipe-maintainers:
    - jonmmease
